### PR TITLE
Updated small comment

### PR DESCRIPTION
**Pull request by Gunsola**
HI Manish

I have updated new commnet, Please review this.

### CODE REVIEW

**Comment by Manish-Gunsola** [comment]
HI Arti

Please add more details to that comment.

Thanks
Manish

**Comment by Manish-Gunsola** [comment]
Hi Manish 
I have updated new commnets.

Thanks
Arti

**Comment by Gunsola** [comment]
HI manish

I added commnet.

Thanks Arti

**Comment by Manish-Gunsola** [comment]
HI Arti

Go to add new changes.

**Pull request merged**
